### ISSUE TITLE
Validation should also check for not existing or misspelled fields

### ISSUE THREAD

**Issue by alanbrande** [Light-it-labs/laravel_google_jobs#3]
It would be great if validation would check for not existing or misspelled fields in the array.

**Comment by cjreysayago** [comment]
This can be easily implemented extending the `Validator` Class `src/app/Validator.php`
I was thinking about having some kind of skeleton model that represents a valid GJob instance, that way we can validate whether the actual instance is well structured or not.

```php
class GJobValidator extends Validator 
{
   // Add specific Gjob structure validation logic
}
```
Any suggestions?
