### ISSUE TITLE
Default value for @context and @type attributes

### ISSUE THREAD

**Issue by JuanNitram** [Light-it-labs/laravel_google_jobs#5]
## Description
Right now we have to set the @context and @type attributes for every job offer that we have, it would be great if these attributes had default values as seems to be constants according to google documentation.

[
...
'@context' => 'http://schema.org',
'@type' => 'JobPosting'
...
]

**Comment by cjreysayago** [comment]
Hi @JuanNitram Looks nice! Can you please attach the documentation section that says these values are constants?

**Comment by JuanNitram** [comment]
Hey @cjreysayago, here you have [Google Jobs Documentation](https://developers.google.com/search/docs/data-types/job-posting)

**Comment by cjreysayago** [comment]
Implemented on 01db8ac
